name: Call Reusable Workflow

on:
  push:
    branches: [main]

jobs:
    call-build:
        uses: ./.github/workflows/reusable-build.yml
        with:
            app_name: "my-web-app"
            environment: "dev"
        secrets:
            docker_token: ${{ secrets.DOCKER_TOKEN }}
