name: Run test for py

on: push

jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
            
            - name: Check out code
              uses: actions/checkout@v4
            
            - name: Install Python
              run: sudo apt update && sudo apt install -y python3
            
            
            - name: Run script
              run: |
                python3 test.py
            
           