name: External Trigger

on:
  repository_dispatch:
    types: [deploy-request]

jobs:
  external:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Env: ${{ github.event.client_payload.environment }}"