name: First Workflow

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: 
    inputs:
      environment:
        description: "Enter Environment"
        required: true
        default: "staging"
  
jobs:
  greet_stage_1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from Github Actions Runner"

      - name: Show Date
        run: date

      - name: check who are you in runner
        run: whoami

      - name: show current branch
        run: |
          echo 'Branch: "${{ github.ref_name }}"'

      - name: List files
        run: ls -la

      - name: Show OS
        run: uname -a

      - name: Print inputs
        run: |
          echo "Environment is ${{ github.event.inputs.environment }}"
