name: Hosted Runners

on:
  push:


jobs:
  ubuntu-job:
    runs-on: ubuntu-latest

    steps:

      - run: |
          echo "OS: ubuntu"
          hostname
          whoami

      - name: Check tools
        run: |
          docker --version
          python --version
          node --version
          git --version

  windows-job:
    runs-on: windows-latest

    steps:

      - run: |
          echo "OS: Windows"
          hostname
          whoami

  mac-job:
    runs-on: macos-latest

    steps:

      - run: |
          echo "OS: macos"
          hostname
          whoami