name: PR check

on:
  pull_request:
    branches: [main]

jobs:
  pr-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print PR info
        run: |
          echo "PR check running for branch == ${{ github.head_ref }}"