name: Reusable Build

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
        default: write your app name
      environment:
        required: true
        type: string
        default: staging
    secrets:
      docker_token:
        required: true
    outputs:
        build_version:
            value: ${{ jobs.build.outputs.version }}


jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
        version: ${{ steps.set_version.outputs.version }}

    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: print build info
        run: |
          echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"

      - name: check secret
        run: |
          if [ -n "${{ secrets.docker_token }}" ]; then
            echo "Docker token is set: true"
          fi

      - id: set_version
        run: echo "version=v1.0-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

