name: Scheduled Tasks

on:
  schedule:
    - cron: '30 2 * * 1'
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  schedule-job:
    runs-on: ubuntu-latest

    steps:
      
      - run: |
         echo "Triggered by: ${{ github.event.schedule }}"

      - name: Health check
        run: curl -I https://google.com