name: secrets-demo

on: push

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    environment: dev 

    steps:
      - name: Check secret exists
        run: |
          if [ -z "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "Secret is not set"
            exit 1
          else
            echo "Secret is set"
          fi

      - name: Try printing secret
        run: echo "${{ secrets.MY_SECRET_MESSAGE }}"

      - name: Use secret as env
        env:
            SECRET_MSG: ${{ secrets.MY_SECRET_MESSAGE }}
        run: echo "Using secret safely"

      - name: Create file
        run: echo "This is my report" > report.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: report
            path: report.txt
            