name: Self hosted

on:
  push:

jobs:
  self-jobs:
    runs-on: [self-hosted, my-windows-runner]

    steps:

    - name: Show hostname
      run: hostname

    - name: Show working dir 
      run: pwd

    - name: Create files
      run: |
        echo "Hello from github actions to self hosted runner" > test.txt